<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sld_SliderContainer</name>
   <tag></tag>
   <elementGuidId>caa68cf0-f9b0-4775-97bc-417e751b511a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'content')]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='range']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='range']</value>
   </webElementProperties>
</WebElementEntity>
